#!/usr/bin/env python3
"""
수집된 데이터 정제 파이프라인.

작업:
1. 중복 제거 (해시 기반)
2. 언어 감지 + 한국어 필터링
3. 코드 품질 필터 (구문 오류, 자동 생성 파일)
4. 개인정보 마스킹 (이메일, 전화번호, 주민번호)
5. 청크 분할
6. 최종 데이터셋 생성 (.bin for pretrain, .jsonl for SFT)

사용법:
    python scripts/data/cleaner.py \\
        --input data/raw \\
        --output data/processed
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ============================================================
# 정규식 패턴 (개인정보, 자동 생성 코드 등)
# ============================================================

# 개인정보
EMAIL_PATTERN = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b")
PHONE_PATTERN = re.compile(r"01[016789]-?\d{3,4}-?\d{4}")
RRN_PATTERN = re.compile(r"\d{6}-?\d{7}")  # 주민번호
CARD_PATTERN = re.compile(r"\d{4}-?\d{4}-?\d{4}-?\d{4}")  # 신용카드
SSH_KEY_PATTERN = re.compile(r"-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----")
API_KEY_PATTERN = re.compile(
    r"(?i)(api[_-]?key|secret|token|password)\s*[=:]\s*['\"]?([a-zA-Z0-9_\-]{20,})['\"]?"
)

# 자동 생성 파일 시그니처
AUTO_GEN_PATTERNS = [
    re.compile(r"DO NOT EDIT", re.IGNORECASE),
    re.compile(r"automatically generated", re.IGNORECASE),
    re.compile(r"@generated", re.IGNORECASE),
    re.compile(r"// Code generated by"),
    re.compile(r"# Generated by"),
]

# 너무 반복적인 텍스트
def is_too_repetitive(text: str, threshold: float = 0.3) -> bool:
    """텍스트가 너무 반복적인지 체크."""
    lines = text.split("\n")
    if len(lines) < 10:
        return False
    line_counts = Counter(lines)
    most_common_count = line_counts.most_common(1)[0][1]
    return most_common_count / len(lines) > threshold


def has_korean(text: str, min_chars: int = 50) -> bool:
    """한국어 포함 여부."""
    korean_count = sum(1 for c in text if "\uAC00" <= c <= "\uD7A3")
    return korean_count >= min_chars


def korean_ratio(text: str) -> float:
    """한국어 비율."""
    if not text:
        return 0.0
    korean = sum(1 for c in text if "\uAC00" <= c <= "\uD7A3")
    return korean / len(text)


def is_auto_generated(text: str) -> bool:
    """자동 생성 파일인지 체크."""
    head = text[:1000]  # 앞 1000자만 체크
    return any(p.search(head) for p in AUTO_GEN_PATTERNS)


def mask_pii(text: str) -> str:
    """개인정보 마스킹."""
    text = EMAIL_PATTERN.sub("[EMAIL]", text)
    text = PHONE_PATTERN.sub("[PHONE]", text)
    text = RRN_PATTERN.sub("[RRN]", text)
    text = CARD_PATTERN.sub("[CARD]", text)
    text = SSH_KEY_PATTERN.sub("[SSH_KEY]", text)
    text = API_KEY_PATTERN.sub(r"\1=[REDACTED]", text)
    return text


def normalize_whitespace(text: str) -> str:
    """공백 정규화."""
    # 탭 → 공백
    text = text.replace("\t", "    ")
    # 연속된 공백 줄임
    text = re.sub(r" {3,}", "  ", text)
    # 너무 많은 빈 줄
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


@dataclass
class CleanedItem:
    """정제된 데이터 항목."""
    source: str          # github, blog, public
    type: str            # code, text, mixed
    language: str        # python, korean, javascript 등
    content: str
    meta: dict


class DataCleaner:
    """데이터 정제기."""

    def __init__(self, input_dir: Path, output_dir: Path):
        self.input_dir = input_dir
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.stats = {
            "total_input": 0,
            "deduplicated": 0,
            "removed_short": 0,
            "removed_long": 0,
            "removed_auto_gen": 0,
            "removed_no_korean": 0,
            "removed_repetitive": 0,
            "kept": 0,
        }

        self.seen_hashes: set[str] = set()

    def clean_all(self):
        """모든 데이터 정제."""
        all_items: list[CleanedItem] = []

        # 1. GitHub 데이터
        github_dir = self.input_dir / "github"
        if github_dir.exists():
            logger.info("GitHub 데이터 정제 중...")
            for item in self._process_github(github_dir):
                all_items.append(item)
                if len(all_items) % 1000 == 0:
                    logger.info(f"  처리: {len(all_items)}개")

        # 2. 블로그 데이터
        blogs_dir = self.input_dir / "blogs"
        if blogs_dir.exists():
            logger.info("블로그 데이터 정제 중...")
            for item in self._process_blogs(blogs_dir):
                all_items.append(item)
                if len(all_items) % 100 == 0:
                    logger.info(f"  처리: {len(all_items)}개")

        # 3. 결과 저장
        self._save_pretrain_data(all_items)
        self._save_sft_data(all_items)

        # 4. 통계
        self._print_stats()

    def _process_github(self, github_dir: Path):
        """GitHub 데이터 처리."""
        for repo_dir in github_dir.iterdir():
            if not repo_dir.is_dir():
                continue

            files_jsonl = repo_dir / "files.jsonl"
            if not files_jsonl.exists():
                continue

            with open(files_jsonl, encoding="utf-8") as f:
                for line in f:
                    self.stats["total_input"] += 1
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    cleaned = self._clean_code_file(data)
                    if cleaned:
                        yield cleaned

    def _clean_code_file(self, data: dict) -> CleanedItem | None:
        """코드 파일 정제."""
        content = data.get("content", "")

        # 길이 체크
        if len(content) < 100:
            self.stats["removed_short"] += 1
            return None
        if len(content) > 50_000:
            self.stats["removed_long"] += 1
            return None

        # 자동 생성 파일 제거
        if is_auto_generated(content):
            self.stats["removed_auto_gen"] += 1
            return None

        # 반복적 내용 제거
        if is_too_repetitive(content):
            self.stats["removed_repetitive"] += 1
            return None

        # 정제
        content = mask_pii(content)
        content = normalize_whitespace(content)

        # 중복 체크
        content_hash = hashlib.md5(content.encode()).hexdigest()
        if content_hash in self.seen_hashes:
            self.stats["deduplicated"] += 1
            return None
        self.seen_hashes.add(content_hash)

        self.stats["kept"] += 1
        return CleanedItem(
            source="github",
            type="code",
            language=data.get("language", "unknown"),
            content=content,
            meta={
                "repo": data.get("repo"),
                "path": data.get("path"),
                "stars": data.get("stars", 0),
                "has_korean": data.get("has_korean", False),
            },
        )

    def _process_blogs(self, blogs_dir: Path):
        """블로그 데이터 처리."""
        for blog_dir in blogs_dir.iterdir():
            if not blog_dir.is_dir():
                continue

            articles_jsonl = blog_dir / "articles.jsonl"
            if not articles_jsonl.exists():
                continue

            with open(articles_jsonl, encoding="utf-8") as f:
                for line in f:
                    self.stats["total_input"] += 1
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    cleaned = self._clean_blog_article(data)
                    if cleaned:
                        yield cleaned

    def _clean_blog_article(self, data: dict) -> CleanedItem | None:
        """블로그 글 정제."""
        text = data.get("text", "")
        code_blocks = data.get("code_blocks", [])

        # 한국어 확인
        if not has_korean(text):
            self.stats["removed_no_korean"] += 1
            return None

        # 길이 체크
        if len(text) < 200:
            self.stats["removed_short"] += 1
            return None
        if len(text) > 100_000:
            self.stats["removed_long"] += 1
            return None

        # 정제
        text = mask_pii(text)
        text = normalize_whitespace(text)

        # 본문 + 코드 결합 (markdown 형식)
        full_content = text
        if code_blocks:
            full_content += "\n\n## 코드 예시\n\n"
            for cb in code_blocks:
                lang = cb.get("language", "")
                code = cb.get("code", "")
                full_content += f"```{lang}\n{code}\n```\n\n"

        # 중복 체크
        content_hash = hashlib.md5(full_content.encode()).hexdigest()
        if content_hash in self.seen_hashes:
            self.stats["deduplicated"] += 1
            return None
        self.seen_hashes.add(content_hash)

        self.stats["kept"] += 1
        return CleanedItem(
            source="blog",
            type="mixed",
            language="korean",
            content=full_content,
            meta={
                "blog_name": data.get("blog_name"),
                "title": data.get("title"),
                "url": data.get("url"),
            },
        )

    def _save_pretrain_data(self, items: list[CleanedItem]):
        """Pretrain 데이터로 저장 (단순 텍스트)."""
        output_file = self.output_dir / "pretrain_corpus.txt"
        with open(output_file, "w", encoding="utf-8") as f:
            for item in items:
                f.write(item.content)
                f.write("\n\n<|endoftext|>\n\n")

        size_mb = output_file.stat().st_size / 1e6
        logger.info(f"Pretrain corpus 저장: {output_file} ({size_mb:.1f}MB)")

    def _save_sft_data(self, items: list[CleanedItem]):
        """SFT 데이터로 저장 (블로그 글만, instruction 형식)."""
        output_file = self.output_dir / "sft_data.jsonl"
        count = 0
        with open(output_file, "w", encoding="utf-8") as f:
            for item in items:
                if item.source != "blog":
                    continue

                # 블로그 글을 instruction 형식으로 변환
                title = item.meta.get("title", "")
                if not title:
                    continue

                example = {
                    "messages": [
                        {"role": "user", "content": title},
                        {"role": "assistant", "content": item.content},
                    ],
                    "source": item.meta.get("blog_name"),
                }
                f.write(json.dumps(example, ensure_ascii=False) + "\n")
                count += 1

        logger.info(f"SFT data 저장: {output_file} ({count}개)")

    def _print_stats(self):
        logger.info("=" * 60)
        logger.info("정제 완료!")
        logger.info(f"  입력: {self.stats['total_input']:,}개")
        logger.info(f"  유지: {self.stats['kept']:,}개")
        logger.info(f"  중복 제거: {self.stats['deduplicated']:,}개")
        logger.info(f"  너무 짧음: {self.stats['removed_short']:,}개")
        logger.info(f"  너무 김: {self.stats['removed_long']:,}개")
        logger.info(f"  자동 생성: {self.stats['removed_auto_gen']:,}개")
        logger.info(f"  한국어 없음: {self.stats['removed_no_korean']:,}개")
        logger.info(f"  반복적: {self.stats['removed_repetitive']:,}개")
        logger.info("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="데이터 정제")
    parser.add_argument("--input", default="data/raw", help="입력 디렉토리")
    parser.add_argument("--output", default="data/processed", help="출력 디렉토리")
    args = parser.parse_args()

    cleaner = DataCleaner(
        input_dir=Path(args.input),
        output_dir=Path(args.output),
    )
    cleaner.clean_all()


if __name__ == "__main__":
    main()
