// Git PR 자동 생성 유틸리티
// 큰 작업 종료 시 변경사항을 새 branch 로 push 하고 GitHub PR 을 생성한다.
// gh CLI 가 설치되어 있어야 하며, 안전 가드로 기본 draft 모드 + main/master 직접 push 차단을 적용한다.

import { spawn } from "child_process";

export interface PRCreationResult {
  success: boolean;
  prUrl?: string;
  branch?: string;
  commitHash?: string;
  error?: string;
}

export interface PRCreationOptions {
  workspaceRoot: string;
  title: string;
  body: string;
  baseBranch?: string;       // 기본 main
  branchName?: string;        // 미지정 시 자동 생성
  draft?: boolean;            // 기본 true (안전)
  filesChanged?: string[];    // 명시적 파일 목록 (없으면 git add -A)
}

interface ExecResult {
  stdout: string;
  stderr: string;
  code: number;
}

export class GitPRCreator {
  /**
   * 변경사항을 새 branch 로 commit, push 후 gh CLI 로 PR 을 생성한다.
   * 어느 단계든 실패하면 success=false 와 error 를 담아 반환한다.
   */
  async createPR(opts: PRCreationOptions): Promise<PRCreationResult> {
    const cwd = opts.workspaceRoot;

    try {
      // 1. git 가용 확인 (워크스페이스가 git repo 인지)
      await this.exec("git", ["rev-parse", "--show-toplevel"], cwd);

      // 2. 변경사항 있는지 확인
      const status = await this.exec("git", ["status", "--porcelain"], cwd);
      if (!status.stdout.trim()) {
        return { success: false, error: "변경사항이 없습니다" };
      }

      // 3. branch 결정 — main/master 직접 push 차단
      const branch = opts.branchName || this.generateBranchName(opts.title);
      const baseBranch = opts.baseBranch || "main";

      if (branch === "main" || branch === "master") {
        return {
          success: false,
          error: "main/master 브랜치로 직접 PR 생성은 금지되어 있습니다. 새 branch 를 사용하세요.",
        };
      }

      // 현재 branch 확인 — 다르면 checkout (이미 존재하면 -b 없이 checkout)
      const currentBranch = (
        await this.exec("git", ["rev-parse", "--abbrev-ref", "HEAD"], cwd)
      ).stdout.trim();

      if (currentBranch !== branch) {
        const branchExists = await this.branchExists(branch, cwd);
        if (branchExists) {
          await this.exec("git", ["checkout", branch], cwd);
        } else {
          await this.exec("git", ["checkout", "-b", branch], cwd);
        }
      }

      // 4. add + commit
      if (opts.filesChanged?.length) {
        await this.exec("git", ["add", ...opts.filesChanged], cwd);
      } else {
        await this.exec("git", ["add", "-A"], cwd);
      }

      const commitMsg = `${opts.title}\n\n${opts.body}\n\n🤖 Generated by Hwarang AI`;
      await this.exec("git", ["commit", "-m", commitMsg], cwd);
      const commitHash = (await this.exec("git", ["rev-parse", "HEAD"], cwd)).stdout.trim();

      // 5. push
      await this.exec("git", ["push", "-u", "origin", branch], cwd);

      // 6. gh pr create — gh CLI 미설치 시 graceful 에러
      const prArgs = [
        "pr", "create",
        "--title", opts.title,
        "--body", opts.body,
        "--base", baseBranch,
        "--head", branch,
      ];
      if (opts.draft !== false) prArgs.push("--draft");

      let prResult: ExecResult;
      try {
        prResult = await this.exec("gh", prArgs, cwd);
      } catch (e: any) {
        const msg = e?.message || String(e);
        if (/ENOENT|not found|command not found/i.test(msg)) {
          return {
            success: false,
            branch,
            commitHash,
            error: "gh CLI 가 설치되어 있지 않습니다. https://cli.github.com 에서 설치하세요. (commit/push 는 완료됨)",
          };
        }
        throw e;
      }

      const prUrl = prResult.stdout.trim();

      return {
        success: true,
        prUrl,
        branch,
        commitHash,
      };
    } catch (e: any) {
      return { success: false, error: e?.message || String(e) };
    }
  }

  /**
   * 제목으로부터 안전한 branch 이름을 생성한다.
   * 형식: hwarang/YYYY-MM-DD-제목슬러그
   */
  private generateBranchName(title: string): string {
    const slug = title
      .toLowerCase()
      .replace(/[^\w\s가-힣-]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 40);
    const date = new Date().toISOString().slice(0, 10);
    return `hwarang/${date}-${slug}`;
  }

  /**
   * 로컬에 해당 branch 가 이미 존재하는지 확인한다.
   */
  private async branchExists(branch: string, cwd: string): Promise<boolean> {
    try {
      await this.exec("git", ["rev-parse", "--verify", `refs/heads/${branch}`], cwd);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * child_process.spawn 을 Promise 로 감싼 wrapper.
   * 실패 시 stderr 와 함께 Error 를 throw 한다.
   */
  private exec(cmd: string, args: string[], cwd: string): Promise<ExecResult> {
    return new Promise((resolve, reject) => {
      const proc = spawn(cmd, args, { cwd });
      let stdout = "";
      let stderr = "";

      proc.on("error", (err) => {
        reject(err);
      });

      proc.stdout.on("data", (d) => {
        stdout += d.toString();
      });
      proc.stderr.on("data", (d) => {
        stderr += d.toString();
      });
      proc.on("close", (code) => {
        if (code === 0) {
          resolve({ stdout, stderr, code });
        } else {
          reject(new Error(`${cmd} ${args.join(" ")} failed (${code}): ${stderr}`));
        }
      });
    });
  }
}

/**
 * 통합 가이드 (executor.ts):
 *
 *   import { GitPRCreator } from "../utils/git-pr";
 *
 *   case "create_pull_request": {
 *     const creator = new GitPRCreator();
 *     const result = await creator.createPR({
 *       workspaceRoot: this.workspaceRoot,
 *       title: args.title,
 *       body: args.body,
 *       baseBranch: args.base_branch || "main",
 *       draft: args.draft !== false,
 *     });
 *     if (result.success) {
 *       return {
 *         success: true,
 *         output: `PR 생성: ${result.prUrl}\nbranch: ${result.branch}`,
 *       };
 *     }
 *     return { success: false, output: result.error || "PR 생성 실패" };
 *   }
 *
 * TOOL_DEFINITIONS 에 추가:
 *
 *   {
 *     type: "function",
 *     function: {
 *       name: "create_pull_request",
 *       description: "현재 변경사항을 새 브랜치로 push 후 GitHub PR 자동 생성. 큰 작업 마무리에 사용.",
 *       parameters: {
 *         type: "object",
 *         properties: {
 *           title: { type: "string", description: "PR 제목" },
 *           body: { type: "string", description: "PR 본문 (작업 요약, 변경 내용)" },
 *           base_branch: { type: "string", description: "병합 대상 브랜치 (기본: main)" },
 *           draft: { type: "boolean", description: "draft 모드 (기본: true, 안전)" },
 *         },
 *         required: ["title", "body"],
 *       },
 *     },
 *   }
 */
